### ISSUE TITLE
Problema de deploy con Node a vercel

### ISSUE THREAD

**Issue by Martinmessner** [PF-Musicfy/app-Musicfy#250]
Buenas, vi que pudiste subir tu proyecto y deployarlo bien con vercel cosa que no pude hacer, queria saber como hiciste?.
A mi no me deja y lo intente con muchas cosas, tengo una base de datos con mongoDB y lo integre dandole al uri_mongo y todo eso pero tampoco me deploya bien.
Te pregunto porque no tengo a quien preguntarle y todo lo que busque no pude hacer que funcione.
Bueno nada gracias por leer y buena suerte.

**Comment by hugok2k** [comment]
Hola Martin, como estas? recién veo esta issue, es un poco tarde, pero el proyecto lo tenemos en vercel la parte del front y railway en el back.

**Comment by Martinmessner** [comment]
Gracias por responder, si también tuve que utilizar railway para el back
